name: e_nosso
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

  # Adicione o intl aqui, alinhado com os de cima
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true