// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC50d7wbooZgl2Fu-JEr_w2QVB4XdXywpY',
    appId: '1:568534953987:web:77ec4eb703c7457b089e36',
    messagingSenderId: '568534953987',
    projectId: 'enosso-e1144',
    authDomain: 'enosso-e1144.firebaseapp.com',
    storageBucket: 'enosso-e1144.firebasestorage.app',
    measurementId: 'G-V4J0Z6RHSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVTpJt9g6VXnDfk9CKmOdJRoMyhTbVNc',
    appId: '1:568534953987:android:2dd66cb96c59c63b089e36',
    messagingSenderId: '568534953987',
    projectId: 'enosso-e1144',
    storageBucket: 'enosso-e1144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEKLD19twSELjA5JLMFku2DZXHM65420',
    appId: '1:568534953987:ios:ffeb7c146b9d9bbf089e36',
    messagingSenderId: '568534953987',
    projectId: 'enosso-e1144',
    storageBucket: 'enosso-e1144.firebasestorage.app',
    iosBundleId: 'com.example.eNosso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEKLD19twSELjA5JLMFku2DZXHM65420',
    appId: '1:568534953987:ios:ffeb7c146b9d9bbf089e36',
    messagingSenderId: '568534953987',
    projectId: 'enosso-e1144',
    storageBucket: 'enosso-e1144.firebasestorage.app',
    iosBundleId: 'com.example.eNosso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC50d7wbooZgl2Fu-JEr_w2QVB4XdXywpY',
    appId: '1:568534953987:web:1ab8f7af219c8def089e36',
    messagingSenderId: '568534953987',
    projectId: 'enosso-e1144',
    authDomain: 'enosso-e1144.firebaseapp.com',
    storageBucket: 'enosso-e1144.firebasestorage.app',
    measurementId: 'G-S4MFTN5C16',
  );
}
